---
- name: Enable SELinux
  selinux:
    state: enforcing
    policy: targeted

# This prevents a permission denied error when RT tries to use /tmp.
- name: Enable httpd_unified SELinux boolean
  seboolean:
    name: httpd_unified
    state: yes
    persistent: yes

# At some point, may want to roll this into a proper RT policy.
# Right now, it's very convenient to set file contexts from Ansible without
# needing to compile an entirely new policy module and installing it.
- include_vars: file_contexts.yml

- block:
    
    - name: Remove fcontext rules specific to RT
      command: >-
        /sbin/semanage fcontext --delete
        --type {{ item.type }}
        --ftype {{ item.ftype }}
        '{{ item.file_spec }}'
      with_items: "{{ rt_fcontext }}"
      when: rt_fcontext
        
    - name: Create fcontext rules for RT
      command: >-
        /sbin/semanage fcontext --add
        --seuser {{ item.seuser }}
        --type {{ item.type }}
        --ftype {{ item.ftype }}
        '{{ item.file_spec }}'
      with_items: "{{ file_contexts }}"

  when: rt_fcontext != file_contexts
    
- name: Restore default RT file contexts
  file:
    path: /opt/rt4
    state: directory
    recurse: yes
    seuser: _default
    serole: _default
    setype: _default
    selevel: _default
